#:schema https://raw.githubusercontent.com/ghishadow/lapce-schema/main/volt.theme.schema.json
name = "night-owl"
version = "0.0.1"
display-name = "Night Owl theme"
description = "dark colorscheme inspired by the colors of the famous painting by Katsushika Hokusai. (based on Neovim theme)"
author = "ghishadow"
repository = "https://github.com/ghishadow/night-owl"
icon = "assets/owl-icon.png"
color-themes = ["night_owl.toml", "light_owl.toml"]
